#!/bin/bash

OS_TYPE=`uname`
if [ $OS_TYPE == "Linux" ]; then
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ibm/lotus/notes
fi
if [ $OS_TYPE == "Darwin" ]; then
  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Applications/Notes.app/Contents/MacOS
fi

SCRIPT_PATH=`echo $0 | sed -e "s/\/[^\/]*$//"`
echo Running Lotus Notes Google Calendar Sync...
java -jar $SCRIPT_PATH/icalbridge.jar
echo
echo
read -n 1 -p "Press any key to continue"

