#!/bin/bash
# Run Lotus Notes to Google Calendar Synchronizer under Linux and OS X.

# NOTE: If you come up with enhancments to this script, please post
# them to the project's Open Discussion forum:
# https://sourceforge.net/projects/lngooglecalsync/forums  

# The application uses Notes.jar, the Java interface file installed with the
# Lotus Notes client. Notes.jar references some .so files under Linux and .dylib
# files under OS X.
# In particular, make sure the dir containing lsxbe.so or lsxbe.dylib is in the path.
# The default locations for Notes.jar and the library files are hard-coded below.

OS_TYPE=`uname`
if [ $OS_TYPE == "Linux" ]; then
  NOTES_PATH=/opt/ibm/lotus/notes
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NOTES_PATH
fi
if [ $OS_TYPE == "Darwin" ]; then
  NOTES_PATH=/Applications/Notes.app/Contents/MacOS
  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$NOTES_PATH
fi

SCRIPT_PATH=`echo $0 | sed -e "s/\/[^\/]*$//"`
echo Running Lotus Notes Google Calendar Sync...
java -cp $NOTES_PATH/jvm/lib/ext/Notes.jar:$SCRIPT_PATH/icalbridge.jar LotusNotesGoogleCalendarBridge.mainGUI

echo
echo
read -n 1 -p "Press any key to continue"

